version: '2.0'

services:
   wordpress:
     image: thafila:wordpress
     ports:
       - "8070:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpress:8070
       WORDPRESS_DB_HOST: 172.23.0.2:3306
       WORDPRESS_DB_NAME: thafila
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
     networks:
       - dacs2018
networks:
  dacs2018:
    external:
       name: dacs2018